server {
    listen 443 ssl;
    http2 on;
    server_name decoder.qwer.kz;

    root /var/www;
    index index.php index.html index.htm;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    ssl_certificate     /etc/nginx/certs/decoder.qwer.kz.cer;
    ssl_certificate_key /etc/nginx/certs/decoder.qwer.kz.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;

    location /api/ {
        try_files $uri $uri/ /processor.php?$query_string;
    }
    location /swagger {
        return 302 $scheme://$host:$server_port/swagger/;
    }
    location /swagger/ {
        proxy_pass http://swaggerdeco:8080/;
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }


    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass phpdeco:9000;   # имя сервиса php в docker-compose
        fastcgi_index index.php;
        fastcgi_read_timeout 300;
    }

    location ~ /\.ht {
        deny all;
    }
}
